// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const __dirname = dirname(fileURLToPath(import.meta.url));
loadEnv({ path: resolve(__dirname, ".env") });

const databaseUrl = process.env["DATABASE_URL"];
const normalizedDatabaseUrl = databaseUrl?.trim();

if (databaseUrl !== undefined && !normalizedDatabaseUrl) {
  throw new Error(
    "DATABASE_URL is set but empty. Please provide a valid connection string.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  ...(normalizedDatabaseUrl
    ? { datasource: { url: normalizedDatabaseUrl } }
    : {}),
});
